# This file is copied to spec/ when you run "rails generate rspec:install"
ENV["RAILS_ENV"] = "test"
require File.expand_path("../../config/environment", __FILE__)
# Prevent database truncation if the environment is production
# ...
RSpec.configure do |config|
	# ...
	config.add_formatter("json", "rspec_time_runs.json")
  # ...
end
# ...
